networks:
  symfony-network:
    name: symfony-network
    external: true

services:
  app:
    container_name: pass-generator-php
    env_file:
      - .env
    networks:
      - symfony-network
    restart: unless-stopped

  web:
    container_name: dev-caddy-pass-generator
    depends_on:
      - app
    ports:
      - "8950:80"
    networks:
      - symfony-network
    restart: unless-stopped
