version: "3.7"

services:
  app:
    build:
      context: .
      target: php-debug
    volumes:
      - ./:/srv/app
      - ./var:/srv/app/var:rw
      - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    env_file:
      - .env.local
    environment:
      - XDEBUG_MODE=${XDEBUG_MODE:-debug}

  web:
    build:
      target: caddy
      context: .
    volumes:
      - ./public:/srv/app/public:ro
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
